/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LiveJazz {}
  interface ScottFree {
    'activeNotes': string[];
    'octaves': number;
    'playSound': (
    note: string,
    octave: number
    ) => () => void;
  }
  interface ThemKeys {
    'octaves': number;
  }
}

declare global {


  interface HTMLLiveJazzElement extends Components.LiveJazz, HTMLStencilElement {}
  var HTMLLiveJazzElement: {
    prototype: HTMLLiveJazzElement;
    new (): HTMLLiveJazzElement;
  };

  interface HTMLScottFreeElement extends Components.ScottFree, HTMLStencilElement {}
  var HTMLScottFreeElement: {
    prototype: HTMLScottFreeElement;
    new (): HTMLScottFreeElement;
  };

  interface HTMLThemKeysElement extends Components.ThemKeys, HTMLStencilElement {}
  var HTMLThemKeysElement: {
    prototype: HTMLThemKeysElement;
    new (): HTMLThemKeysElement;
  };
  interface HTMLElementTagNameMap {
    'live-jazz': HTMLLiveJazzElement;
    'scott-free': HTMLScottFreeElement;
    'them-keys': HTMLThemKeysElement;
  }
}

declare namespace LocalJSX {
  interface LiveJazz {}
  interface ScottFree {
    'activeNotes'?: string[];
    'octaves'?: number;
    'playSound'?: (
    note: string,
    octave: number
    ) => () => void;
  }
  interface ThemKeys {
    'octaves'?: number;
  }

  interface IntrinsicElements {
    'live-jazz': LiveJazz;
    'scott-free': ScottFree;
    'them-keys': ThemKeys;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'live-jazz': LocalJSX.LiveJazz & JSXBase.HTMLAttributes<HTMLLiveJazzElement>;
      'scott-free': LocalJSX.ScottFree & JSXBase.HTMLAttributes<HTMLScottFreeElement>;
      'them-keys': LocalJSX.ThemKeys & JSXBase.HTMLAttributes<HTMLThemKeysElement>;
    }
  }
}


