/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ScottFree {
    'octaves': number;
  }
}

declare global {


  interface HTMLScottFreeElement extends Components.ScottFree, HTMLStencilElement {}
  var HTMLScottFreeElement: {
    prototype: HTMLScottFreeElement;
    new (): HTMLScottFreeElement;
  };
  interface HTMLElementTagNameMap {
    'scott-free': HTMLScottFreeElement;
  }
}

declare namespace LocalJSX {
  interface ScottFree {
    'octaves'?: number;
  }

  interface IntrinsicElements {
    'scott-free': ScottFree;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'scott-free': LocalJSX.ScottFree & JSXBase.HTMLAttributes<HTMLScottFreeElement>;
    }
  }
}


